### ISSUE TITLE
bug in SFH basis use

### ISSUE THREAD

**Issue by changhoonhahn** [changhoonhahn/gqp_mc#47]
There seems to be some inconsistencies in how the SFH bases are applied. Check the SFH calculations in the methods `get_SFR` and `_fsps_model`. 

Also check that `_emulator` and `_fsps_model` generate the same SED for the same parameter values

**Comment by changhoonhahn** [comment]
Once I went back to v0.3.0 of `python-fsps`, the emulator and fsps model are consistent. Hence, this issue seems to have been a red herring. 

@kgb0255 Could you confirm this by running [DESI_speculator_comparison.ipynb](https://github.com/changhoonhahn/gqp_mc/blob/master/nb/DESI_speculator_comparison.ipynb) and checking that you reproduce the same results?

**Comment by kgb0255** [comment]
@changhoonhahn I don't see the exactly same spectra as yours at the end of the notebook (maybe because I ran the whole notebook multiple times), but it seems that the plotted spectra have good agreement. Attached the result below.
<img width="396" alt="Screen Shot 2020-08-14 at 7 06 54 PM" src="https://user-images.githubusercontent.com/57269223/90303252-5b1c5980-de61-11ea-9fad-b71607977448.png">

**Comment by changhoonhahn** [comment]
@kgb0255 Great. You have a different spectrum since you have a different random seed. What important is the agreement between the emulator and fsps.
